driver = "rts"

[rts]
spi_device = "./fake-spi"
gdo0_gpio = 18
pigpiod_addr = "127.0.0.1:8888"
frame_count = 4

[telis.gpio]
up = 26
stop = 19
down = 13
select = 6
led1 = 21
led2 = 20
led3 = 16
led4 = 12
prog = 5